#!/bin/bash
set -o errexit
grunt full-build
scp Hive.zip 192.254.186.53:Hive.zip
echo "Unpacking..."
ssh 192.254.186.53 "cd Hive && rm -rf * && mv ../Hive.zip . && unzip -q Hive.zip"
echo "Deployed."
