#!/bin/bash
set -o errexit
grunt full-build
scp Hive.zip threewestwinds.com:Hive.zip
echo "Unpacking..."
ssh threewestwinds.com "cd Hive && rm -rf * && mv ../Hive.zip . && unzip -q Hive.zip"
echo "Deployed."
